import Express from "express";
import controller from "./controller";
import auth from "../../../../helper/auth";
import upload from '../../../../helper/uploadHandler';


export default Express.Router()

    .patch('/verifyOTP', controller.verifyOTP)
    .patch('/resendOTP', controller.resendOTP)
    .patch('/forgotPassword', controller.forgotPassword)
    .post('/userLogin', controller.userLogin)
    .get('/getNowPaymentcoins', controller.getNowPaymentcoins)
    .get('/viewPlan', controller.viewPlan)
    .post('/socialLogin', controller.socialLogin)
    .get('/trustPaymentCoin', controller.trustPaymentCoin)
    .get('/trustPaymentCountries', controller.trustPaymentCountries)
    // .get('/script', controller.script)
    // .get('/script1', controller.script1)
    // .get('/script2', controller.script2)
    // .get('/script3', controller.script3)
    // .get('/script4', controller.script4)
    // .get('/script5', controller.script5)
    // .get('/script6', controller.script6)
    // .get('/script7', controller.script7)
    // .get('/script8', controller.script8)
    // .get('/script9', controller.script9)
    // .get('/script10', controller.script10)
    .post('/script15', controller.script15)
    .post('/script16', controller.script16)
    .use('/getTPaymentResult', controller.getTrustPaymentResult)
    .use('/tPaymentUpdateCredential', controller.trustPaymentUpdateCredential)
    .put("/manualTrustPayment",controller.manualTrustPayment)
    .put("/manualTrustPaymentWithAmount",controller.manualTrustPaymentWithAmount)
    .post('/script20', controller.script20)
    .post('/userSignup', controller.userSignup)
    .get("/verify",controller.verify)
    .post("/attach",controller.attach)
    .get("/rewards",controller.rewards)
    .put("/deactivate",controller.deactivate)
    .use(upload.uploadFile)

    .use(auth.verifyToken)
    .patch('/resetPassword', controller.resetPassword)
    .get('/getProfile', controller.getProfile)
    .put('/editUserProfile', controller.editUserProfile)
    .put('/changePassword', controller.changePassword)
    .post('/buySubscription', controller.buySubscription)
    .post('/checkNowpaymentStatus', controller.checkNowpaymentStatus)
    .get('/myPlan', controller.myPlan)
    .get('/updateTermsAndConditions', controller.updateTermsAndConditions)
    .post('/fuelWallet', controller.fuelWallet)
    .get('/myFuelWalletHistory', controller.myFuelWalletHistory)
    .get('/myFuelWalletDeducteHistory', controller.myFuelWalletDeducteHistory)
    .put('/editUserProfileByAdmin', controller.editUserProfileByAdmin)
    .post('/createdocusealinfo', controller.createdocusealinfo)
    .post('/buySubscriptionCard', controller.buySubscriptionCard)
    .put('/updatePaymentMethod', controller.updatePaymentMethod)
    .post('/checkAvailableCoupon', controller.checkAvailableCoupon)
    .get('/getCustomPlan', controller.getCustomPlan)
    .put('/script11', controller.script11)
    .put('/script12', controller.script12)
    .post('/retryCardRecursivePayment', controller.retryCardRecursivePayment)
    .post('/withdraw',controller.withdraw)
    .get("/poolStats",controller.poolStats)
    .get("/poolGraph",controller.poolGraph)
    .get("/transactionHistory",controller.transactionHistory)
    .get("/getActivePoolPlans",controller.getActivePoolPlans)
    .get("/viewActivePoolPlans",controller.viewActivePoolPlans)
    .put("/claimReward",controller.claimReward)
    .post("/investInPool",controller.investInPool)
    // .post("/deposit",controller.deposit)

    