module.exports = Object.freeze({
    ACTIVE: 'ACTIVE',
    BLOCK: 'BLOCK',
    DELETE: 'DELETE',
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REJECTED:'REJECTED',
    INACTIVE:"INACTIVE"
})